provider:
  name: faas
  gateway: http://129.213.194.84:8080
functions:
  codecardpy:
    lang: python3
    handler: ./codecardpy
    image: jit2600/codecardpy:latest
    environment:
      content_type: application/json
